- name: Create a custom Docker network
  hosts: all
  become: true
  tasks:
    - name: Create network
      community.docker.docker_network:
        name: custom_network
        driver: bridge
        state: present

