- name: Pull the official PostgreSQL Docker image
  community.docker.docker_image:
    name: "{{ postgres_image }}"
    source: pull
  notify: restart postgres container

- name: Run PostgreSQL container
  community.docker.docker_container:
    name: "{{ postgres_container_name }}"
    image: "{{ postgres_image }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "{{ host_port }}:{{ container_port }}"
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_DB: "{{ postgres_db }}"
